### ISSUE TITLE
Why not just use the gitlab sdk

### ISSUE THREAD

**Issue by lwydyby** [MamaShip/MR-Tracker#15]
https://github.com/xanzy/go-gitlab

**Comment by MamaShip** [comment]
Why do you think this is the official SDK? In my opinion, it's just a Go wrapper for the GitLab API. It's not provided by the official GitLab organization.

Anyway, the go-gitlab library seems quite good.
In fact, GitLab itself provides functionality to generate a change log too. And some people think that MR-Tracker is reinventing the wheel.

When I was developing MR-Tracker, I felt that only the GitLab API could offer the features I needed, so I implemented it by making API calls. 
Fortunately, doing so is not too complicated. We have encapsulated the calls to the GitLab API using the same approach in order to simplify the program logic.
